### ISSUE TITLE
handle columns markup in two-column mode

### ISSUE THREAD

**Issue by jdutant** [jdutant/columns#4]
Check whether the class option "twocolumn" is set. If so, handle column breaks and column spans in the document and (optionally) generate HTML output with two columns. Provide a global two-columns option that sets the class option twocolumn.

**Comment by badumont** [comment]
LaTeX's builtin `twocolumn` class option doesn't render like a `multicols` environment with two columns, so that I think that this filter should stick to handling the `multicol` package, even when the number of columns is set globally to two. Of course, it would be nice to create a *twocolumn* filter!
